// Code generated by pluginator on BootstrapProviderKubeadmCRDRegister; DO NOT EDIT.
package register

import (
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1alpha2"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the BootstrapProviderKubeadmChart CRD scheme into kustomize
type BootstrapProviderKubeadmCRDRegisterPlugin struct {
}

//nolint: golint

func (p *BootstrapProviderKubeadmCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1alpha2.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *BootstrapProviderKubeadmCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewBootstrapProviderKubeadmCRDRegisterPlugin() resmap.TransformerPlugin {
	return &BootstrapProviderKubeadmCRDRegisterPlugin{}
}
